spring.application.name=ms-customer-service

# PostgreSQL datasource (matches docker-compose.yml)
spring.datasource.url=jdbc:postgresql://localhost:5434/dbPrueba
spring.datasource.username=kahuaski
spring.datasource.password=ADmin123!
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Prevent Spring Boot from trying to create an embedded DB when Postgres is available
spring.datasource.initialization-mode=always

# Base context path for all endpoints
server.servlet.context-path=/api
